# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [push]

name: CI
   
jobs:
  ci:
    name: Build, test, check and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      # builds, tests and checks the formatting
      - uses: rust-lang/simpleinfra/github-actions/simple-ci@master
        with:
          check_fmt: true    

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
        
